### ISSUE TITLE
Unify main thread naming with mainline Robolectric

### ISSUE THREAD

**Issue by mannodermaus** [apter-tech/junit5-robolectric-extension#52]
I'm investigating the integration of the [Roborazzi](https://github.com/takahirom/roborazzi) library with JUnit 5 via this extension and it works pretty well already. However, one thing I found is that it expects the main thread spun up by Robolectric to conform to a specific naming convention. [You can see here](https://github.com/takahirom/roborazzi/blob/bcee2ce20c717589e83ac175efef52994100aba7/include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/DefaultFileNameGenerator.kt#L67-L73) that they expect the thread to have either `Main Thread` or `Test worker` in its name.

In the mainline Robolectric repository, the naming convention seems to be `SDK xx Main Thread` ([link](https://github.com/robolectric/robolectric/blob/81831fc059a6f098466063cb95b8df670929ee8d/robolectric/src/main/java/org/robolectric/internal/AndroidSandbox.java#L67)), but the JUnit 5 extension uses `Main-Thread-<threadId>-SDK-xx` instead ([link](https://github.com/apter-tech/junit5-robolectric-extension/blob/ff3ea6d2e4e82c9f5cd1228757e60655431ad9b8/robolectric-extension/src/main/kotlin/tech/apter/junit/jupiter/robolectric/internal/JUnit5RobolectricAndroidSandbox.kt#L35)). This causes the file name lookup function from Roborazzi to fail to detect the test method correctly.

FWIW, I have to submit some changes to Roborazzi anyway so that it can fully embrace JUnit 5, so I can also just extend their main thread checking logic while I'm at it. However, can we unify this name to match up with mainline Robolectric, or is there a reason for the difference (parallel test execution, maybe)? I can provide a pull request if necessary. Thanks!

**Comment by warnyul** [comment]
@mannodermaus I think we can change back the naming for `SDK {apiLevel} Main Thread {threadId}`

**Comment by warnyul** [comment]
Updated in [0.5.2](https://github.com/apter-tech/junit5-robolectric-extension/releases/tag/0.5.2)
