### ISSUE TITLE
Possibility to reduce targetCompatibility to Java 11?

### ISSUE THREAD

**Issue by mannodermaus** [apter-tech/junit5-robolectric-extension#66]
I'm trying to introduce support for JUnit 5 to [Roborazzi](https://github.com/takahirom/roborazzi), a helpful screenshot testing library that integrates with Robolectric. That library builds its JARs with a target compatibility of Java 11, and this clashes when paired with junit5-robolectric-extension, which outputs Java 17-compatible bytecode. We could keep using Java 17 to build its artifacts, but would you consider dropping its output to Java 11 compatibility? This way, we could extend the potential user base to all projects that still run on Android Gradle Plugin 7.x, for instance. If not, we can probably consider a split target requirement over at the Roborazzi repository (so that only the JUnit 5 stuff requires Java 17 compatibility). Thanks in advance!

**Comment by warnyul** [comment]
A new version available with Java 11 support: https://github.com/apter-tech/junit5-robolectric-extension/releases/tag/0.7.0
