### ISSUE TITLE
README doesn't explain how to "Enable JUnit Platform Launcher Interceptors"

### ISSUE THREAD

**Issue by mgroth0** [apter-tech/junit5-robolectric-extension#89]
In the README it says to "Enable JUnit Platform Launcher Interceptors" but doesn't say how to or point to any other documentation for how to do this.

**Comment by warnyul** [comment]
Yeah, I should update the readme to make it clearer. If you apply the plugin as described in the `README.md`, it will enable the JUnit Platform Launcher Interceptors.
